"""lib/nginx_converter.py — convert a plain nginx conf to a Jinja2 .j2 template.

Transformations applied
-----------------------
directive           before                              after
---------           ------                              -----
server_name         server_name example.com;            server_name {{ hostname }};
auth_basic          auth_basic "My App";                auth_basic "{{ service_name }} - {{ user_name }}";
auth_basic_user_file auth_basic_user_file /etc/...;     auth_basic_user_file {{ htpasswd_path }};
proxy_pass          proxy_pass http://myapp-web:80;     proxy_pass http://{{ container_prefix }}web:80;
                    (only when service_name_hint given and prefix matches)

All other content is preserved verbatim.  ${ENV_VAR} expressions are left
untouched — they are resolved by nginx at runtime via environment substitution.
"""

from __future__ import annotations

import re
from pathlib import Path

_HEADER_TPL = """\
# {stem}.nginx.conf.j2 — generated by gen_nginx_template.py
#
# Template variables resolved at registration time by user_provision_tool:
#   {{{{ hostname }}}}          e.g. {hint}-alice-0.example.com
#   {{{{ container_prefix }}}}  e.g. {hint}-user_alice-0-
#   {{{{ htpasswd_path }}}}     absolute path to the generated .htpasswd file
#   {{{{ user_name }}}}
#   {{{{ service_name }}}}
#   {{{{ label }}}}
#   {{{{ domain_name }}}}
#   {{{{ network_name }}}}
#
# NOTE: proxy_pass targets have been rewritten where possible:
#   • Hosts matching a compose service name → {{{{ container_prefix }}}}<name>
#   • Hosts starting with the service name hint → {{{{ container_prefix }}}}<suffix>
#   Review and adjust any remaining literal container names manually.
#
"""


def convert_nginx(
    text: str,
    service_name_hint: str = "",
    compose_service_names: list[str] | None = None,
) -> str:
    """Apply Jinja2 substitutions to the text of a plain nginx conf.

    Parameters
    ----------
    service_name_hint:
        Provision service name used as a prefix hint to rewrite proxy_pass
        targets (e.g. ``myapp-web`` → ``{{ container_prefix }}web``).
    compose_service_names:
        Service keys from the companion docker-compose.yml.  When a proxy_pass
        host matches one of these names exactly, the entire host is replaced
        with ``{{ container_prefix }}<name>`` so it resolves to the actual
        deployed container name at render time.
    """

    # server_name — replace all name tokens after the keyword
    text = re.sub(
        r'([ \t]*server_name[ \t]+)[^\n;]+(;)',
        r'\1{{ hostname }}\2',
        text,
    )

    # auth_basic string
    text = re.sub(
        r'([ \t]*auth_basic[ \t]+)"[^"]*"(;)',
        r'\1"{{ service_name }} - {{ user_name }}"\2',
        text,
    )

    # auth_basic_user_file path
    text = re.sub(
        r'([ \t]*auth_basic_user_file[ \t]+)\S+(;)',
        r'\1{{ htpasswd_path }}\2',
        text,
    )

    # If no auth_basic block exists at all, inject one before the first proxy_pass
    if not re.search(r'[ \t]*auth_basic\b', text):
        def _inject_auth(m: re.Match) -> str:
            indent = re.match(r'^([ \t]*)', m.group(0)).group(1)
            auth_lines = (
                indent + 'auth_basic "{{ service_name }} - {{ user_name }}";\n' +
                indent + 'auth_basic_user_file {{ htpasswd_path }};\n'
            )
            return auth_lines + m.group(0)
        text = re.sub(r'[ \t]*proxy_pass[ \t]+\S+;', _inject_auth, text, count=1)

    # --- Build set of compose service names for fast lookup ---
    compose_names: set[str] = set()
    if compose_service_names:
        compose_names = {n.lower() for n in compose_service_names}

    # proxy_pass — rewrite host part when it references a service or matches hint
    if service_name_hint or compose_names:
        hint_esc = re.escape(service_name_hint) if service_name_hint else None

        def _repl_proxy(m: re.Match) -> str:
            scheme = m.group(1)      # "http://" or "https://"
            host = m.group(2)        # container name or hostname
            port_path = m.group(3)   # ":port" and/or "/path", may be empty
            tail = m.group(4)        # ";" or whitespace terminator

            # 1) Exact match against a compose service name → replace whole host
            if compose_names and host.lower() in compose_names:
                return (
                    f"proxy_pass {scheme}"
                    f"{{{{ container_prefix }}}}{host}{port_path}{tail}"
                )

            # 2) Prefix match against service_name_hint → strip hint, keep suffix
            if hint_esc:
                stripped = re.sub(
                    rf'^{hint_esc}[-_]?', '', host, flags=re.IGNORECASE
                )
                if stripped != host:
                    return (
                        f"proxy_pass {scheme}"
                        f"{{{{ container_prefix }}}}{stripped}{port_path}{tail}"
                    )

            return m.group(0)

        text = re.sub(
            r'proxy_pass\s+(https?://)([a-zA-Z0-9_-]+)((?::\d+)?(?:/[^\s;]*)?)(;)',
            _repl_proxy,
            text,
        )

    return text


def make_header(filename: str, service_name_hint: str) -> str:
    hint = service_name_hint or filename
    return _HEADER_TPL.format(stem=filename, hint=hint)


def nginx_file_to_template(
    input_path: str,
    output_path: str,
    service_name_hint: str = "",
    compose_service_names: list[str] | None = None,
) -> None:
    """Convert a plain nginx conf file to a Jinja2 template and write output_path.

    Parameters
    ----------
    compose_service_names:
        Service keys from the companion docker-compose.yml.  Passed through to
        :func:`convert_nginx` so proxy_pass targets matching a compose service
        name are rewritten to ``{{ container_prefix }}<name>``.
    """
    src = Path(input_path)
    text = src.read_text()
    hint = service_name_hint or src.stem
    header = make_header(src.name, hint)
    converted = convert_nginx(text, hint, compose_service_names)
    Path(output_path).write_text(header + converted)
