"""lib/nginx_converter.py — convert a plain nginx conf to a Jinja2 .j2 template.

Transformations applied
-----------------------
directive           before                              after
---------           ------                              -----
server_name         server_name example.com;            server_name {{ hostname }};
auth_basic          auth_basic "My App";                auth_basic "{{ service_name }} - {{ user_name }}";
auth_basic_user_file auth_basic_user_file /etc/...;     auth_basic_user_file {{ htpasswd_path }};
proxy_pass          proxy_pass http://myapp-web:80;     proxy_pass http://{{ container_prefix }}web:80;
                    (only when service_name_hint given and prefix matches)

All other content is preserved verbatim.  ${ENV_VAR} expressions are left
untouched — they are resolved by nginx at runtime via environment substitution.
"""

from __future__ import annotations

import re
from pathlib import Path

_HEADER_TPL = """\
# {stem}.nginx.conf.j2 — generated by gen_nginx_template.py
#
# Template variables resolved at registration time by user_provision_tool:
#   {{{{ hostname }}}}          e.g. {hint}-alice-0.example.com
#   {{{{ container_prefix }}}}  e.g. {hint}-user_alice-0-
#   {{{{ htpasswd_path }}}}     absolute path to the generated .htpasswd file
#   {{{{ user_name }}}}
#   {{{{ service_name }}}}
#   {{{{ label }}}}
#   {{{{ domain_name }}}}
#   {{{{ network_name }}}}
#   {{{{ https }}}}             boolean, True when HTTPS is enabled
#   {{{{ ssl_certificate_path }}}}      /provision/ssl/{{{{ domain_name }}}}/fullchain.pem
#   {{{{ ssl_certificate_key_path }}}}  /provision/ssl/{{{{ domain_name }}}}/privkey.pem
#
# NOTE: proxy_pass targets have been rewritten where possible:
#   • Hosts matching a compose service name → {{{{ container_prefix }}}}<name>
#   • Hosts starting with the service name hint → {{{{ container_prefix }}}}<suffix>
#   Review and adjust any remaining literal container names manually.
#
# NOTE: ssl_certificate and ssl_certificate_key paths have been replaced with
#   template variables.  Wrap HTTPS server blocks in {{% if https %}}...{{% endif %}}
#   to conditionally enable TLS.
#
"""


def convert_nginx(
    text: str,
    service_name_hint: str = "",
    compose_service_names: list[str] | None = None,
) -> str:
    """Apply Jinja2 substitutions to the text of a plain nginx conf.

    Parameters
    ----------
    service_name_hint:
        Provision service name used as a prefix hint to rewrite proxy_pass
        targets (e.g. ``myapp-web`` → ``{{ container_prefix }}web``).
    compose_service_names:
        Service keys from the companion docker-compose.yml.  When a proxy_pass
        host matches one of these names exactly, the entire host is replaced
        with ``{{ container_prefix }}<name>`` so it resolves to the actual
        deployed container name at render time.
    """

    # server_name — replace all name tokens after the keyword
    text = re.sub(
        r'([ \t]*server_name[ \t]+)[^\n;]+(;)',
        r'\1{{ hostname }}\2',
        text,
    )

    # auth_basic string
    text = re.sub(
        r'([ \t]*auth_basic[ \t]+)"[^"]*"(;)',
        r'\1"{{ service_name }} - {{ user_name }}"\2',
        text,
    )

    # auth_basic_user_file path
    text = re.sub(
        r'([ \t]*auth_basic_user_file[ \t]+)\S+(;)',
        r'\1{{ htpasswd_path }}\2',
        text,
    )

    # ssl_certificate path → {{ ssl_certificate_path }}
    text = re.sub(
        r'([ \t]*ssl_certificate[ \t]+)\S+(;)',
        r'\1{{ ssl_certificate_path }}\2',
        text,
    )

    # ssl_certificate_key path → {{ ssl_certificate_key_path }}
    text = re.sub(
        r'([ \t]*ssl_certificate_key[ \t]+)\S+(;)',
        r'\1{{ ssl_certificate_key_path }}\2',
        text,
    )

    # If no auth_basic block exists at all, inject one before the first proxy_pass
    if not re.search(r'[ \t]*auth_basic\b', text):
        def _inject_auth(m: re.Match) -> str:
            indent = re.match(r'^([ \t]*)', m.group(0)).group(1)
            auth_lines = (
                indent + 'auth_basic "{{ service_name }} - {{ user_name }}";\n' +
                indent + 'auth_basic_user_file {{ htpasswd_path }};\n'
            )
            return auth_lines + m.group(0)
        text = re.sub(r'[ \t]*proxy_pass[ \t]+\S+;', _inject_auth, text, count=1)

    # --- Build set of compose service names for fast lookup ---
    compose_names: set[str] = set()
    if compose_service_names:
        compose_names = {n.lower() for n in compose_service_names}

    # --- Wrap / auto-generate HTTPS server blocks ---
    # Helper to split text into server blocks (preserving non-server content).
    def _split_server_blocks(t: str):
        blocks = re.split(r'(^[ \t]*server\s*\{)', t, flags=re.MULTILINE)
        result: list[dict[str, Any]] = []
        i = 0
        while i < len(blocks):
            chunk = blocks[i]
            if re.match(r'^[ \t]*server\s*\{', chunk):
                # Collect the full server block via brace counting
                block = chunk
                depth = chunk.count('{') - chunk.count('}')
                i += 1
                while i < len(blocks) and depth > 0:
                    next_chunk = blocks[i]
                    depth += next_chunk.count('{') - next_chunk.count('}')
                    block += next_chunk
                    i += 1
                result.append({"is_server": True, "text": block})
            else:
                if chunk:
                    result.append({"is_server": False, "text": chunk})
                i += 1
        return result

    _has_ssl_listen = bool(re.search(r'listen\s+[^;]*\bssl\b', text))
    if _has_ssl_listen:
        # Existing HTTPS blocks: wrap them + redirect blocks in {% if https %}.
        parts = _split_server_blocks(text)
        out: list[str] = []
        for p in parts:
            if p["is_server"]:
                block = p["text"]
                if re.search(r'listen\s+[^;]*\bssl\b', block):
                    out.append('\n{% if https %}\n' + block + '\n{% endif %}\n')
                elif re.search(r'return\s+301\s+https://', block):
                    out.append('\n{% if https %}\n' + block + '\n{% endif %}\n')
                else:
                    out.append(block)
            else:
                out.append(p["text"])
        text = ''.join(out)
    else:
        # No HTTPS blocks in source → auto-generate them from HTTP blocks.
        parts = _split_server_blocks(text)
        out: list[str] = []
        for p in parts:
            if p["is_server"]:
                block = p["text"]
                # Only auto-generate HTTPS for blocks with listen 80 (not other ports).
                if re.search(r'listen\s+[^;]*\b80\b', block) and not re.search(r'listen\s+[^;]*\bssl\b', block):
                    https_block = block
                    # Replace listen 80 (with optional modifiers) → listen 443 ssl
                    https_block = re.sub(
                        r'listen\s+80(\s+[^;]*)?;',
                        r'listen 443 ssl\1;',
                        https_block,
                    )
                    # Inject ssl_certificate directives after the listen 443 ssl line
                    https_block = re.sub(
                        r'(listen\s+443\s+ssl[^;]*;)',
                        r'\1\n    ssl_certificate {{ ssl_certificate_path }};\n    ssl_certificate_key {{ ssl_certificate_key_path }};',
                        https_block,
                    )
                    out.append(block)
                    out.append('\n{% if https %}\n' + https_block + '\n{% endif %}\n')
                else:
                    out.append(block)
            else:
                out.append(p["text"])
        text = ''.join(out)

    # proxy_pass — rewrite host part when it references a service or matches hint
    if service_name_hint or compose_names:
        hint_esc = re.escape(service_name_hint) if service_name_hint else None

        def _repl_proxy(m: re.Match) -> str:
            scheme = m.group(1)      # "http://" or "https://"
            host = m.group(2)        # container name or hostname
            port_path = m.group(3)   # ":port" and/or "/path", may be empty
            tail = m.group(4)        # ";" or whitespace terminator

            # 1) Exact match against a compose service name → replace whole host
            if compose_names and host.lower() in compose_names:
                return (
                    f"proxy_pass {scheme}"
                    f"{{{{ container_prefix }}}}{host}{port_path}{tail}"
                )

            # 2) Prefix match against service_name_hint → strip hint, keep suffix
            if hint_esc:
                stripped = re.sub(
                    rf'^{hint_esc}[-_]?', '', host, flags=re.IGNORECASE
                )
                if stripped != host:
                    return (
                        f"proxy_pass {scheme}"
                        f"{{{{ container_prefix }}}}{stripped}{port_path}{tail}"
                    )

            return m.group(0)

        text = re.sub(
            r'proxy_pass\s+(https?://)([a-zA-Z0-9_-]+)((?::\d+)?(?:/[^\s;]*)?)(;)',
            _repl_proxy,
            text,
        )

    return text


def make_header(filename: str, service_name_hint: str) -> str:
    hint = service_name_hint or filename
    return _HEADER_TPL.format(stem=filename, hint=hint)


def nginx_file_to_template(
    input_path: str,
    output_path: str,
    service_name_hint: str = "",
    compose_service_names: list[str] | None = None,
) -> None:
    """Convert a plain nginx conf file to a Jinja2 template and write output_path.

    Parameters
    ----------
    compose_service_names:
        Service keys from the companion docker-compose.yml.  Passed through to
        :func:`convert_nginx` so proxy_pass targets matching a compose service
        name are rewritten to ``{{ container_prefix }}<name>``.
    """
    src = Path(input_path)
    text = src.read_text()
    hint = service_name_hint or src.stem
    header = make_header(src.name, hint)
    converted = convert_nginx(text, hint, compose_service_names)
    Path(output_path).write_text(header + converted)
